### ISSUE TITLE
freegeoip.net will look up your IP address for you.

### ISSUE THREAD

**Issue by Droogans** [HackerHouseYT/Smart-Mirror#1]
From [their site](https://freegeoip.net/).

> If no IP or hostname is provided, then your own IP is looked up.

It would definitely make this system more user friendly to people who pack up their smart mirror and move across the country.

You can also use this data to determine the country code, so you only need to over ride it should you want news from another country. Now, all they need to do is get an api token for weather information!

**Comment by atainter** [comment]
Good point, I didn't think about that. If you make a pr I can merge it in. Otherwise, I can change it tonight.

**Comment by Droogans** [comment]
This got covered in #4 and #6.
