### ISSUE TITLE
 Forecast.io is being relaunched as darksky.net!

### ISSUE THREAD

**Issue by filvi** [HackerHouseYT/Smart-Mirror#10]
[solved] Hi first of all great job! I wonder if the python script is it already compatible with new website https://darksky.net? As forecast.io reports " Forecast.io is being relaunched as darksky.net! Read our [announcement ](http://blog.darksky.net/introducing-darksky-net/) for more information."

**Comment by kebrx** [comment]
Just looked at the code,  in smartmirror.py, [Line 118](https://github.com/HackerHouseYT/Smart-Mirror/blob/master/smartmirror.py#L118), the API request is going against api.darksky.net, so I'd venture a guess and say it's compatible.  Hope this helps!

**Comment by atainter** [comment]
This has already been changed.
