### ISSUE TITLE
Implementing Google Calender issue..

### ISSUE THREAD

**Issue by sajuran123** [HackerHouseYT/Smart-Mirror#109]
Hey

Did anyone implement the "**Google Calender**" yet? 

I personally got the calendar title on the screen and the API up running from the "**Python Quickstart**". 

My question is how to get the API from "**Python Quickstart**" implemented in the exisiting code from HackerShack?

Thank you

Sajuran

**Comment by big1surg** [comment]
https://github.com/big1surg/smart_mirror/blob/master/module_calendar.py

i broke it down into a module and then just called it from the main page. its not the best way to do it but it works

        # calender, added this to the main frame
        self.calender = module_calendar.Calendar(self.bottomFrame)
        self.calender.pack(side = LEFT, anchor=S, padx=50, pady=50)

![image](https://user-images.githubusercontent.com/16482529/43859081-8d1a600a-9b04-11e8-842f-5f4c9d0477d4.png)

**Comment by harrysprogramming** [comment]
hi is there any way you could update your module please because the api client is discontinued
