### ISSUE TITLE
how to get git working

### ISSUE THREAD

**Issue by LudoStes** [HackerHouseYT/Smart-Mirror#11]
Typing in command in myPI :
  pi@myPI ~/.ssh $ git clone git@github.com:HackerHouseYT/Smart-Mirror.git
Then I get this message : 
   Cloning into 'Smart-Mirror'...
  Permission denied (publickey).
  The remote end hung up unexpectedly

What I am doing wrong here? I am quit new in this..
I installed the git succesfull with command 
   sudo apt-get install git-all

just wondering what I am doing wrong here.

**Comment by atainter** [comment]
You have to add an ssh key to github. See https://help.github.com/articles/generating-an-ssh-key/
