### ISSUE TITLE
Problem during Install your dependencies

### ISSUE THREAD

**Issue by rkalra4** [HackerHouseYT/Smart-Mirror#120]
![2019-12-07-194523_1920x1080_scrot](https://user-images.githubusercontent.com/58641950/70382971-0700c300-192b-11ea-9002-ed52cec2199b.png)
![2019-12-07-194754_1920x1080_scrot](https://user-images.githubusercontent.com/58641950/70382972-0700c300-192b-11ea-8954-aa6b8c6af044.png)

I'm getting an error while installing the dependencies. I've looked all the other threads with the same issue but nothing helped me. So, can someone kindly help me with my issue.
I've also attached the screenshot showing that I do have requirements.txt file but still I'm having the issue.

**Comment by Arbazkhan4712** [comment]
Use cd Smart Mirror then use pip install

**Comment by rkalra4** [comment]
> Use cd Smart Mirror then use pip install

Thanks a lot for the help
