### ISSUE TITLE
Fullscreen

### ISSUE THREAD

**Issue by Warm4kerT** [HackerHouseYT/Smart-Mirror#15]
I am using an raspberry screen for this project and when i run the python file just the clock and date appeared on the screen. Can you help me with this problem?

**Comment by atainter** [comment]
Hmm works for me. Do you have all of the config values set in the smartmirror.py file? What is your country code? You might need a special country code for news. 
<img width="1059" alt="screen shot 2016-10-16 at 3 53 13 pm" src="https://cloud.githubusercontent.com/assets/7866859/19421556/d2899804-93b8-11e6-8c3d-4720abba857b.png">

**Comment by Warm4kerT** [comment]
Yes i set all config values. I test it on my laptop and worked just fine. Does exist any way that i can adjust the resolution on the .py file?

**Comment by atainter** [comment]
It should autoscale to the correct resolution. Is your pi connected to the internet?

**Comment by Warm4kerT** [comment]
yes it is connected. the py file does not correct the resolution.

**Comment by smileyn64** [comment]
Hi,
Maybe you can try to change the background color of each frame with a different color.
it will allow you to see if all the frames are shown and maybe empty of text.

Here the modification for the backgroung, top and bottom frame:
```
class FullscreenWindow:
...
        self.topFrame = Frame(self.tk, background = '**yellow**')
        self.bottomFrame = Frame(self.tk, background = '**green**')
```

Also, are you hitting 'Enter' to switch to the fullscreen display?
I smell a minimum resolution 'non full screen' superior to the piTFT display.
When switching to full screen, it should force the scaling.

Otherwise there is a minimum resolution requirement to this project to be defined.

**Comment by Warm4kerT** [comment]
yes i'mnhitting enter. thanks i will try that

**Comment by atainter** [comment]
Sorry, you're right. It doesn't correct resolution, it auto scales to the screen size if you press enter. Can you post a screenshot? That might help with debugging.

**Comment by Warm4kerT** [comment]
![img_20161017_173227_933](https://cloud.githubusercontent.com/assets/22871788/19446423/8bef973a-9490-11e6-8661-f53d618eb485.jpg)

**Comment by atainter** [comment]
Okay, this is definitely a scaling/layout issue. The clock component fills the whole space so the other components can't be displayed. I'll parameterize the text size tonight so that it can be changed to scale on small screens.

**Comment by Warm4kerT** [comment]
Thanks man. You are the man

**Comment by atainter** [comment]
Sorry, haven't been able to get to this. Will comment when updated.

**Comment by Warm4kerT** [comment]
thanks

**Comment by atainter** [comment]
Pull the latest changes. I added parameters for font sizes.

**Comment by Warm4kerT** [comment]
Thanks a lot i will test it

**Comment by Warm4kerT** [comment]
Well i test it and it wasn't enough to show everything in the screen. Can i reduce the space between the clock and the weather. Is there any way that i can remove the News, because in my country isn't supported.
Thanks a lot for the help.

**Comment by smileyn64** [comment]
For moving the frames you can play with the 'padx' & 'pady' parameters in the class FullScreenWindow.
If you want to remove the news, try by commenting (with # sign) the lines for news frame in the same class.
It should work.

**Comment by atainter** [comment]
Yes, there are quite a few padding options that need to be adjusted. I'm not sure if I can parameterize all of those.

**Comment by bergsm** [comment]
Adjust the padding options doesn't seem to work. Once the frame moves too far one way (like the towards the center) it gets cut off.
