### ISSUE TITLE
Can't clone repository

### ISSUE THREAD

**Issue by King3060** [HackerHouseYT/Smart-Mirror#18]
I can't clone the repository. I enter: 
git clone git@github.com:HackerHouseYT/Smart-Mirror.git 
and it just returns:
Cloning into 'Smart-Mirror'...
Permission denied (publickey).
fatal: The remote end hung up unexpectedly

**Comment by King3060** [comment]
also I click the green button to download it but nothing happens

**Comment by atainter** [comment]
You need to add an ssh key to github: https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/
