### ISSUE TITLE
Error when running smartmirror.py

### ISSUE THREAD

**Issue by kenthmf** [HackerHouseYT/Smart-Mirror#23]
Cloned the files.
Updated the IP and Weather API token then saved the smartmirror.py.
Confirmed following the procedure as instructed in the video and tried download the file again but having same issue.

Having following error when running:

pi@kenthpi:~/Smart-Mirror $ python smartmirror.py 
Traceback (most recent call last):
  File "smartmirror.py", line 142, in get_weather
    r = requests.get(location_req_url)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 60, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 407, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
Error: ('Connection aborted.', gaierror(-2, 'Name or service not known')). Cannot get weather.

**Comment by King3060** [comment]
R u connected to the internet?

**Comment by kenthmf** [comment]
Thanks.
I added the Latitude, Longitude value to the script and rerun the script then it works.
Seems like the  Latitude, Longitude value cannot be set to None.

In my case, no need to tweek the URL.

**Comment by King3060** [comment]
So it works 100% now?

**Comment by Ctian011597** [comment]
how to set the Latitude, Longitude value?
please help me @kenthmf

**Comment by kenthmf** [comment]
you can find following 2 lines in the script.
---------------------------------------------------------
latitude = None # Set this if IP location lookup does not work for you (must be a string)
longitude = None # Set this if IP location lookup does not work for you (must be a string)
---------------------------------------------------------

go to any website which offer the latitude, longtitude value such as 
http://www.latlong.net/
http://www.findlatitudeandlongitude.com/

get the value and replace the 'None' with the value.
