### ISSUE TITLE
Not really an issue. But don't know where to ask.

### ISSUE THREAD

**Issue by King3060** [HackerHouseYT/Smart-Mirror#24]
![14772514009261958839801](https://cloud.githubusercontent.com/assets/22923258/19628903/7cbcc8e4-9960-11e6-8bca-ed558ea88b28.jpg)
![14772515832101079388629](https://cloud.githubusercontent.com/assets/22923258/19628914/e140f394-9960-11e6-85ab-982bb0d90b50.jpg)

I was just wondering if any one could help me. I added random messages in the middle of the screen using the calendar class as a template. But I can't seem to figure out how to update it so it prints a new message after a couple of minutes. Thanks for any help.

**Comment by Ctian011597** [comment]
mr. @King3060 
please send me your codes.
thank you let us make this happen 👍 

cristianbalunan@gmail.com

**Comment by liquid1** [comment]
mr. @King3060  please send me your code because i am facing issues in weather, i sort out the errors in news but unable to debug in the weather section.
thanks
liquid7127@gmail.com

**Comment by liquid1** [comment]
i figured out the errors.
no need to send your code.
thanks
