### ISSUE TITLE
No "Wind.png" in the assets

### ISSUE THREAD

**Issue by Zblay** [HackerHouseYT/Smart-Mirror#33]
Hello, 

And thanks for this project, i love it. 

I ran into an issue today : There's no "Wind.png" in the assets so i added one to my own Smart-Mirror but thing is the Image i used is CC-BY, so the author name is to be mentionned, can anyone find a CC "Wind.png" ( or even create one ? )

Cheers

**Comment by King3060** [comment]
You might be running smartmirror.py from the wrong directory. Also make sure you have not made saved other copies outside the Smart-Mirror directory.

**Comment by Zblay** [comment]
https://github.com/HackerHouseYT/Smart-Mirror/tree/master/assets
I might be wrong but i see no "Wind.png" in there

**Comment by atainter** [comment]
Sorry about that. Just added an icon for Wind.png.
