### ISSUE TITLE
Display

### ISSUE THREAD

**Issue by seanblackwell** [HackerHouseYT/Smart-Mirror#35]
So I know this is probably an issue with my display settings on my monitor or something but the weather and new are being cutoff. any suggestions?

**Comment by King3060** [comment]
Try and mess around with padx and pady

**Comment by seanblackwell** [comment]
how does one do that?

**Comment by King3060** [comment]
look for padx and pady at the bottom of the code. padx should be 100 and pady should be 60. padx moves something horizontally and pady moves stuff vertivally.

**Comment by seanblackwell** [comment]
Thank you!!!
