### ISSUE TITLE
cant get weather?

### ISSUE THREAD

**Issue by liquid1** [HackerHouseYT/Smart-Mirror#40]
please elaborate and help me with the issue..
Traceback (most recent call last):
  File "smartmirror.py", line 158, in get_weather
    weather_obj = json.loads(r.text)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
Error: No JSON object could be decoded. Cannot get weather.

(and i have added the API token)

**Comment by liquid1** [comment]
i figured out every error related to news and weather.
i am disappointed for your response.
 i even mailed you on gmail but even no reply from there.
Anyways thanks for this great opportunity for keeping this open source.
![smartmirror](https://cloud.githubusercontent.com/assets/24705320/21470085/3b836dd0-ca9b-11e6-8841-0321d6f6e0ce.JPG)

**Comment by rosegoldthakur** [comment]
@liquid1  hey could you please explain that how you fixed that above issue ? i am struggling with the same error right now. Also is the Secret Key the API TOKEN ? Please help!!

**Comment by liquid1** [comment]
send the screenshot of your weather code..

**Comment by rosegoldthakur** [comment]
@liquid1 hey I have got it to work now. I was not deleting the parenthesis before and after my TOKEN. Everything is working good for me now. Thank you :)

**Comment by liquid1** [comment]
no problem. if you will face any other problem feel free to ask.

**Comment by seonghun0312** [comment]
hey @liquid1, I have same error. I know it's kinda late to ask, but can you fix mine too? thanx

**Comment by jamesbetterman** [comment]
hey @liquid1 i know i am kinda late but do you think you could show me whats wrong? ive got screenshots. 
![2017-01-25-102002_1280x1024_scrot](https://cloud.githubusercontent.com/assets/25329940/22298994/18eeb846-e2e8-11e6-9a22-5ff613d3e04c.png)
![2017-01-25-102034_1280x1024_scrot](https://cloud.githubusercontent.com/assets/25329940/22298993/18ed2a4e-e2e8-11e6-8870-5f20f6d35868.png)

**Comment by enkuu** [comment]
I kinda have a same problem here guys. Anyone got a solution for this?

**Comment by aRandomGadjee** [comment]
@jamesbetterman Your token, You only need the token code, not the URL I believe

**Comment by nfao2** [comment]
hi can you help me with my issue? i keep getting this 
in get_weather temperature2 = "%s%s" %(str(int(weather_obj['currently']['temperature'])), degree_sign) KeyError: 'currently' Error: 'currently'. Cannot get weather.
