### ISSUE TITLE
Error: 'currently'

### ISSUE THREAD

**Issue by LuckyLuke009** [HackerHouseYT/Smart-Mirror#42]
Hi there,

I hope anyone can help me with this. Everything works, except the wheater.
I always get this message when I start it up:
`Traceback (most recent call last):
  File "smartmirror.py", line 161, in get_weather
    temperature2 = "%s%s" %(str(int(weather_obj['currently']['temperature'])), degree_sign)
KeyError: 'currently'
Error: 'currently'. Cannot get weather.
`

I also put in the secret code as it should be.

Thanks and greets from Germany

Lukas

**Comment by liquid1** [comment]
have you figure out the error or you need help?

**Comment by voodoolights** [comment]
I have the same problem. could you share how you solved it please?
Thank you in advance!

**Comment by nfao2** [comment]
I have the same error too!! How did you fix it?
