### ISSUE TITLE
Text doesn't display fully

### ISSUE THREAD

**Issue by ajayjjain** [HackerHouseYT/Smart-Mirror#59]
On my monitor, the text describing the weather and the news articles does not displays the entire String (shown in the images below). How can I fix it?
![img_0079](https://cloud.githubusercontent.com/assets/17077267/24277410/dc739ab2-100a-11e7-9508-961f0b6e3e69.JPG)
![img_0284](https://cloud.githubusercontent.com/assets/17077267/24277411/dc7551f4-100a-11e7-8e7b-d7d900137a15.JPG)

**Comment by meganelizedwards** [comment]
I'm having the same problem... hmmm?

**Comment by meganelizedwards** [comment]
I figured it out! You have to change the text size in the code. There's a section towards the beginning where it lists 4 different text sizes: 

xlarge_text_size = 50 
large_text_size = 25 
medium_text_size = 12 
small_text_size = 10

Those are the numbers I put in and everything fits well now. It might vary depending on the size of your monitor. 

Hope this helps!

**Comment by abduls060** [comment]
Either you can change the text size or I would recommend to change the value of padding (padx and pady) under the _init_ function of the class FullscreenWindow . For all the three frames (clock, weather and news) I put padx=25 and pady=60.
It worked for me.
Hope it works for you......!!!!

**Comment by delahoya1** [comment]
my news down at the bottom doesn't show any clue why ?
