### ISSUE TITLE
How to make use of the news?

### ISSUE THREAD

**Issue by markferreira01** [HackerHouseYT/Smart-Mirror#73]
Has anyone figured out a way to take the news headline and scroll the text? Or even better scroll the article that's tied to the headline?

**Comment by markferreira01** [comment]
Ops didn't mean to close it.

**Comment by PWRxPSYCHO** [comment]
To scroll the text you could create a Text widget and then add a scroll. (Check Tkinter documentation) and put all the headlines in there, and then set the size to show only 5 articles. Once you call the method again to refresh the articles you could have it scroll up to fill in the new text. However, you would want to erase the old headlines after 10 refreshes just so you are not making too many necessary variables. Also to have the articles scroll you could set a timer, display the first headline, then after x amount of time begin to display the article by calling the RSS feed Dictionary key related to the article.  Then change the widget in the bottom to a scrolling text box and have the article scroll at a speed you set until finished. Then go to the next one.

**Comment by markferreira01** [comment]
Hmmm...good suggestion. I'll take a look at this. Thanks for the idea!
