### ISSUE TITLE
Screen going blank over time

### ISSUE THREAD

**Issue by SpencerHalse** [HackerHouseYT/Smart-Mirror#85]
Hi again,

Another issue I just ran into is that the screen is going blank over about 15 minutes without being touched.

I am unsure if this is an issue with the program or with the raspberry Pi firmware.

Anyhow, I was wondering if anyone knows how to get this fixed.

Any help would be appreciated!

Thanks all,
Spencer.

**Comment by jendit** [comment]
Hi Spencer,

that is a Raspberry Pi related issue.
Basically, it is the standby timer for the HDMI port.

For me, the following worked:

At the current user home directory, go to .config/lxsession/LXDE-pi/ and edit the autostart

Here add the following lines:
@xset s noblank
@xset s off
@xset -dpms

Save the file and restart the Raspberry Pi.

You can check afterwards if the settings work by the command: xset q

It should display this information in the output:
Screen Saver:
prefer blanking:  no ...
...
DPMS is Disabled

Regards,
Jens
