### ISSUE TITLE
Cant clone the repository(Permission Denied)

### ISSUE THREAD

**Issue by werd-drew** [HackerHouseYT/Smart-Mirror#89]
pi@pi:~ $ git clone git@github.com:HackerHouseYT/Smart-Mirror.git
Cloning into 'Smart-Mirror'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

I installed git before trying this via $ sudo apt-get install git-all

Please help

**Comment by sudo21** [comment]
Try git clone git://github.com/HackerHouseYT/Smart-Mirror
