### ISSUE TITLE
forecast.io

### ISSUE THREAD

**Issue by jjedmondson** [HackerHouseYT/Smart-Mirror#9]
line  118  forecast.io changed to darksky.net Solved weather problem for me.

**Comment by atainter** [comment]
If you make a PR, I'll merge it.

**Comment by klombo120** [comment]
I'm still getting an error at line 120 after changing to darksky.net. Any ideas?

weather_obj = json.loads(r.text)

**Comment by atainter** [comment]
@klombo120 Make sure you update the API token

@jjedmondson fixed
